-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.analytics_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  metric_date date NOT NULL,
  total_active_users integer DEFAULT 0,
  total_steps_logged bigint DEFAULT 0,
  avg_steps_per_user numeric DEFAULT 0,
  total_calories_burned numeric DEFAULT 0,
  avg_sleep_hours numeric DEFAULT 0,
  total_water_intake_ml bigint DEFAULT 0,
  challenges_active integer DEFAULT 0,
  new_challenges_completed integer DEFAULT 0,
  total_points_distributed bigint DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT analytics_daily_pkey PRIMARY KEY (id),
  CONSTRAINT analytics_daily_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid,
  action character varying NOT NULL,
  resource_type character varying,
  resource_id uuid,
  changes jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.challenge_participants (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  challenge_id uuid NOT NULL,
  user_id uuid NOT NULL,
  org_id uuid NOT NULL,
  progress_value integer DEFAULT 0,
  rank integer,
  is_completed boolean DEFAULT false,
  completed_date date,
  joined_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challenge_participants_pkey PRIMARY KEY (id),
  CONSTRAINT challenge_participants_challenge_id_fkey FOREIGN KEY (challenge_id) REFERENCES public.wellness_challenges(id),
  CONSTRAINT challenge_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT challenge_participants_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.challenges (
  id text NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text, 'completed'::text, 'draft'::text])),
  points integer DEFAULT 0,
  start_date date,
  end_date date,
  targeting text DEFAULT 'company-wide'::text CHECK (targeting = ANY (ARRAY['company-wide'::text, 'department'::text])),
  departments ARRAY DEFAULT '{}'::text[],
  completion_method text CHECK (completion_method = ANY (ARRAY['self-report'::text, 'manager-verify'::text, 'auto'::text])),
  enrolled integer DEFAULT 0,
  completed integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT challenges_pkey PRIMARY KEY (id)
);
CREATE TABLE public.community_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  post_type character varying NOT NULL DEFAULT 'tip'::character varying CHECK (post_type::text = ANY (ARRAY['recipe'::character varying, 'tip'::character varying, 'blog'::character varying, 'photo'::character varying, 'activity'::character varying]::text[])),
  title character varying,
  content text NOT NULL,
  image_url text,
  tags ARRAY,
  is_pinned boolean NOT NULL DEFAULT false,
  points_awarded integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_posts_pkey PRIMARY KEY (id),
  CONSTRAINT community_posts_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT community_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.habit_streaks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  metric_type character varying NOT NULL,
  current_streak integer NOT NULL DEFAULT 0,
  longest_streak integer NOT NULL DEFAULT 0,
  last_logged_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT habit_streaks_pkey PRIMARY KEY (id),
  CONSTRAINT habit_streaks_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT habit_streaks_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.health_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  metric_date date NOT NULL,
  steps integer DEFAULT 0,
  calories_burned numeric DEFAULT 0,
  water_intake_ml integer DEFAULT 0,
  sleep_hours numeric DEFAULT 0,
  sleep_quality character varying,
  heart_rate_avg integer,
  heart_rate_min integer,
  heart_rate_max integer,
  blood_pressure_systolic integer,
  blood_pressure_diastolic integer,
  weight_kg numeric,
  bmi numeric,
  exercise_minutes integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT health_metrics_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT health_metrics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.leaderboard_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leaderboard_id uuid NOT NULL,
  user_id uuid NOT NULL,
  org_id uuid NOT NULL,
  rank integer NOT NULL,
  score integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaderboard_entries_pkey PRIMARY KEY (id),
  CONSTRAINT leaderboard_entries_leaderboard_id_fkey FOREIGN KEY (leaderboard_id) REFERENCES public.leaderboards(id),
  CONSTRAINT leaderboard_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT leaderboard_entries_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.leaderboards (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  leaderboard_type character varying,
  metric_type character varying,
  period_start date,
  period_end date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leaderboards_pkey PRIMARY KEY (id),
  CONSTRAINT leaderboards_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.nutrition_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  log_date date NOT NULL,
  meal_type character varying NOT NULL,
  food_items text NOT NULL,
  calories numeric DEFAULT 0,
  protein_g numeric,
  carbs_g numeric,
  fat_g numeric,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT nutrition_logs_pkey PRIMARY KEY (id),
  CONSTRAINT nutrition_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT nutrition_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  subscription_tier character varying DEFAULT 'starter'::character varying,
  max_employees integer DEFAULT 100,
  billing_email character varying,
  address text,
  phone character varying,
  tax_id character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  license_status character varying NOT NULL DEFAULT 'active'::character varying CHECK (license_status::text = ANY (ARRAY['trial'::character varying, 'active'::character varying, 'suspended'::character varying, 'expired'::character varying]::text[])),
  license_key character varying,
  license_expires_at timestamp with time zone,
  max_seats integer NOT NULL DEFAULT 100,
  mrr numeric NOT NULL DEFAULT 0,
  stripe_customer_id character varying,
  theme_config jsonb NOT NULL DEFAULT '{}'::jsonb,
  CONSTRAINT organizations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.points_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  points integer NOT NULL,
  transaction_type character varying NOT NULL,
  description text,
  reference_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT points_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT points_transactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT points_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.post_reactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  post_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reaction_type character varying NOT NULL DEFAULT 'like'::character varying CHECK (reaction_type::text = ANY (ARRAY['like'::character varying, 'helpful'::character varying, 'inspiring'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT post_reactions_pkey PRIMARY KEY (id),
  CONSTRAINT post_reactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.community_posts(id),
  CONSTRAINT post_reactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT post_reactions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.reward_redemptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  reward_id uuid NOT NULL,
  points_used integer NOT NULL,
  status character varying DEFAULT 'pending'::character varying,
  redemption_date timestamp with time zone DEFAULT now(),
  completed_date timestamp with time zone,
  tracking_number character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reward_redemptions_pkey PRIMARY KEY (id),
  CONSTRAINT reward_redemptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT reward_redemptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT reward_redemptions_reward_id_fkey FOREIGN KEY (reward_id) REFERENCES public.rewards_catalog(id)
);
CREATE TABLE public.rewards_catalog (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  reward_type character varying,
  points_required integer NOT NULL CHECK (points_required > 0),
  stock_quantity integer CHECK (stock_quantity IS NULL OR stock_quantity >= 0),
  available_quantity integer CHECK (available_quantity IS NULL OR available_quantity >= 0),
  image_url text,
  redemption_instructions text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rewards_catalog_pkey PRIMARY KEY (id),
  CONSTRAINT rewards_catalog_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.user_consents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL,
  consent_type character varying NOT NULL,
  is_consented boolean DEFAULT false,
  consent_date timestamp with time zone,
  revocation_date timestamp with time zone,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_consents_pkey PRIMARY KEY (id),
  CONSTRAINT user_consents_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT user_consents_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.user_points (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  user_id uuid NOT NULL UNIQUE,
  total_points integer DEFAULT 0,
  available_points integer DEFAULT 0,
  redeemed_points integer DEFAULT 0,
  last_updated timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_points_pkey PRIMARY KEY (id),
  CONSTRAINT user_points_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT user_points_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  full_name character varying,
  role character varying NOT NULL,
  department character varying,
  position character varying,
  phone character varying,
  avatar_url text,
  date_of_birth date,
  gender character varying,
  employment_status character varying DEFAULT 'active'::character varying,
  joined_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  wellness_rank character varying NOT NULL DEFAULT 'beginner'::character varying CHECK (wellness_rank::text = ANY (ARRAY['beginner'::character varying, 'veteran'::character varying, 'pro'::character varying]::text[])),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.wellness_challenges (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  challenge_type character varying,
  metric_type character varying,
  target_value integer,
  target_unit character varying,
  start_date date NOT NULL,
  end_date date NOT NULL,
  reward_points integer DEFAULT 100,
  max_participants integer,
  status character varying DEFAULT 'active'::character varying,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT wellness_challenges_pkey PRIMARY KEY (id),
  CONSTRAINT wellness_challenges_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT wellness_challenges_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);